//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesismvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int id_Matricula { get; set; }
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Apellido_p { get; set; }
        public string Apellido_m { get; set; }
        public Nullable<int> Genero { get; set; }
        public string Fecha_Nacimiento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Nacionalidad { get; set; }
    
        public virtual genero genero1 { get; set; }
    }
}
